Rails.application.config.assets.precompile += %w( bootstrap.css )
Rails.application.config.assets.precompile += %w( "bootstrap.min.css" )
Rails.application.config.assets.precompile += %w( "bootswatch" )
Rails.application.config.assets.precompile += %w( "html5shiv" )
Rails.application.config.assets.precompile += %w( "respond.min" )
Rails.application.config.assets.precompile += %w( bootswatch.css )
Rails.application.config.assets.precompile += %w( redmond/jquery-ui.css )
Rails.application.config.assets.precompile += %w( jquery-ui )
