default: &default
  adapter: postgresql
  database: acrasame_testing
  username: wilx
  password: 1234
  encoding: UTF8
  pool: 5

development:
  <<: *default
  
test:
  <<: *default
  
production:
  <<: *default
