default: &default
  adapter: postgresql
  database: agua_development
  username: 
  password: 
  encoding: utf8
  pool: 5

development:
  <<: *default
  
test:
  <<: *default
  
production:
  <<: *default
